name: amaris_consulting
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # State
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1

  #Services
  http: ^1.4.0

  # Number
  intl: ^0.20.2

  #Database
  sqflite: ^2.4.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/core/assets/